version: '3'

services:
    nginx-hzp:
        build: docker/services/nginx
        depends_on:
            - php-hzp
            - mariadb-hzp
        volumes:
            - ./docker/services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/services/nginx/config/sites-enabled:/etc/nginx/sites-enabled/
            - ./:/var/www/html/hzp
        working_dir: /var/www/html/hzp/app
        command: [ 'nginx' ]

    php-hzp:
        build: docker/services/php
        depends_on:
            - mariadb-hzp
        volumes:
            - ./:/var/www/html/hzp
        working_dir: /var/www/html/hzp/app
        entrypoint: [ '../docker/services/php/scripts/entrypoint.sh' ]
        command: [ 'php-fpm' ]

    mariadb-hzp:
        image: mariadb:latest
        env_file:
            - app/.env
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'true'
        volumes:
            - volume-mariadb-hzp:/var/lib/mysql

volumes:
    volume-mariadb-hzp:
